version: '3.8'

services:
  api:
    build:
      context: ./VertrauDesafioTecnico
      dockerfile: Dockerfile
    container_name: vertrau-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=vertrau_db;Username=postgres;Password=#02042216
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: vertrau-postgres
    environment:
      POSTGRES_DB: vertrau_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: